server:
  port: 8080
spring:
  application:
    name: movie-catalog-service
  config:
    import: optional:configserver:http://localhost:8888

resilience4j:
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 2
        maxWaitDuration: 0
    instances:
      backendService: # MUST match @Bulkhead name
        maxConcurrentCalls: 2
#        baseConfig: default
    metrics:
      enabled: true
  circuitbreaker:
    configs:
      default:                   # global default config
        registerHealthIndicator: true
        slidingWindowSize: 2      # track only 2 calls for error calculation
        minimumNumberOfCalls: 1   # compute error rate after 1st call
        failureRateThreshold: 1   # 1% â†’ treat a single failure as threshold exceed
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s

    instances:
      backendService:            # circuit breaker instance name
        baseConfig: default
        slidingWindowType: COUNT_BASED

    metrics:
      enabled: true

  timelimiter:
    configs:
      default:
        timeoutDuration: 4s
    instances:
      backendService:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    endpoint:
      health:
        show-details: always




